### ISSUE TITLE
Error on headless start, missing jar

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.docker#1]
When I try to launch the headless in the docker container, it fails every time...

Here's inside the container : 
```
$ docker run -i -t --entrypoint /bin/bash --rm roiarthurb/gama:1.8.0 
root@af90f06ddb53:/headless# bash gama-headless.sh 
gama-headless.sh
******************************************************************
* GAMA version 1.8                                               *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************

An error has occurred.  See the log file
/headless/configuration/1569068396591.log

root@af90f06ddb53:/headless# cat configuration/1569068396591.log 
!SESSION Sat Sep 21 12:19:56 GMT 2019 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2019-09-21 12:19:56.595
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.400.v20190208-1533.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2019-09-21 12:19:56.597
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:658)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
	at org.eclipse.core.launcher.Main.main(Main.java:44)
```

It looks like the v1.8.0/GAMA_1.8_Linux.zip archive had some default on it or it's missing an unknown dependency....

Any idea @AlexisDrogoul @hqnghi88 ?

**Comment by RoiArthurB** [comment]
Fixed by using GAMA w/ JDK version
